backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "data"
    label: "Data"
    files:
      - name: "gallery"
        label: "Foto Galerij"
        file: "public/data/photos.json"
        fields:
          - label: "Foto's"
            name: "items"
            widget: "list"
            fields:
              - { label: "Afbeelding", name: "image", widget: "image" }
              - { label: "Onderschrift", name: "caption", widget: "string", required: false }
